name: 'Query Issues Output'
description: 'Executes a query to output a set of Issues to disk for processing'
author: 'Christopher Scott (christothes)'
inputs:
  repotoken:
    description: 'The repo GITHUB_TOKEN'
  searchQuery:
    description: 'The query to search for Issues. See https://docs.github.com/en/github/searching-for-information-on-github/searching-issues-and-pull-requests'
    default: ''
runs:
  using: 'node12'
  main: 'dist/index.js'
